<a href="https://colab.research.google.com/github/punishedchumbucket6000/Insurance_Costs.ipynb/blob/main/Insurance_Costs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [ ]:
dataset = pd.read_csv('insurance.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(dataset)

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]


In [ ]:
print(X)

[[19 'female' 27.9 0 'yes']
 [18 'male' 33.77 1 'no']
 [28 'male' 33.0 3 'no']
 ...
 [18 'female' 36.85 0 'no']
 [21 'female' 25.8 0 'no']
 [61 'female' 29.07 0 'yes']]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 1] = le.fit_transform(X[:, 1])
X[:, 4] = le.fit_transform(X[:, 4])

In [ ]:
print(X)

[[19 0 197 0 1]
 [18 1 350 1 0]
 [28 1 331 3 0]
 ...
 [18 0 422 0 0]
 [21 0 146 0 0]
 [61 0 229 0 1]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(y_pred)
print(y_test)

print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))




In [ ]:
X1 = X[:, 0:]
print(X1)

[[19 0 197 0 1]
 [18 1 350 1 0]
 [28 1 331 3 0]
 ...
 [18 0 422 0 0]
 [21 0 146 0 0]
 [61 0 229 0 1]]


In [ ]:
X1 = np.append(arr = np.ones((1338,1)).astype(int), values = X1,axis=1)

In [ ]:
print(X1)

[[1 19 0 197 0 1]
 [1 18 1 350 1 0]
 [1 28 1 331 3 0]
 ...
 [1 18 0 422 0 0]
 [1 21 0 146 0 0]
 [1 61 0 229 0 1]]


In [ ]:
from sklearn.linear_model import LinearRegression
regressor2 = LinearRegression()
regressor2.fit(X, y)

LinearRegression()

In [ ]:
Age=52
Sex=0
BMI=34.5
Children=3
Smoker=0
Index=0

regressor2.predict([
    [Age, Sex, BMI, Children, Smoker]

    ])

array([9231.29])

In [ ]:
47, 1, 24.5, 5, 1
Age=47
Sex=1
BMI=24.5
Children=5
Smoker=1
Index=0

regressor2.predict([
    [Age, Sex, BMI, Children, Smoker]

    ])


array([32454.47])